### ISSUE TITLE
Kubernetes Documentation

### ISSUE THREAD

**Issue by bborysenko** [bborysenko/learning#3]
https://kubernetes.io/docs/home/

## Setup

This section provides instructions for installing Kubernetes and setting up a Kubernetes cluster.

- [ ] [Picking the Right Solution](https://kubernetes.io/docs/setup/pick-right-solution/)
- [ ] Independent Solutions
  - [ ] [Running Kubernetes Locally via Minikube](https://kubernetes.io/docs/getting-started-guides/minikube/)

## Concepts

This section helps you learn about the parts of the Kubernetes system and the abstractions Kubernetes uses to represent your cluster, and helps you obtain a deeper understanding of how Kubernetes works.

## Tasks

This section of the Kubernetes documentation contains pages that show how to do individual tasks.

## Tutorials

This section of the Kubernetes documentation contains tutorials.

- [ ] Kubernetes Basics
  - [ ] [Overview](https://kubernetes.io/docs/tutorials/kubernetes-basics/)
  - [ ] [1. Create a Cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/)
  - [ ] ...
- [ ] [Hello Minikube](https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/)
- [ ] [Kubernetes 101](https://kubernetes.io/docs/user-guide/walkthrough/)
- [ ] [Kubernetes 201](https://kubernetes.io/docs/user-guide/walkthrough/k8s201/)

**Comment by bborysenko** [comment]
В [Kubernetes 101](https://kubernetes.io/docs/user-guide/walkthrough/) не правильно указана точка монтирования для `redis-persistent-storage`:

```
volumeMounts:
  - name: redis-persistent-storage
  mountPath: /data/redis 
```

Монтировать volume [необходимо](https://github.com/docker-library/docs/tree/master/redis#start-with-persistent-storage) на уровень выше - в `/data`.

**Comment by bborysenko** [comment]
Не понятно насколько жива [идея](https://kubernetes.io/docs/user-guide/walkthrough/#multiple-containers) с подом в котором один из контейнеров вытягивает код из Git репозитория при старте.  Реально ли так кто-то делает в миру? 🤔
